BiocManager::install(version = "3.15")
library(BiocManager)
options(repos = BiocManager::repositories())
library("shiny")
library(gridExtra)
library(grid)
library(ggplot2)
library(candisc)
library(shiny)
library(shinydashboard)
library(openxlsx)
library(rms)
library(zoo)
library("rpart")
library("partykit")
library(dplyr)
library(magrittr)
library(formattable)
library(yacca)
library(DT)
library(DEGreport)
library(diceR)
library(pheatmap)
library(tidyr)
library(Hmisc)
library(CCA)
#library("NMF")
source("http://www.statpower.net/R312/CanCorr.r")
#library("rgl")
library("scatterplot3d") # load
library("xtable")
library("rpart")
library("partykit")
library("survminer")
library("rlist")
library("MASS")
library("BBmisc") 

# Read in all the gene expression & clinical factors data
TCGA_GBM_u133a_overall= readRDS("data/TCGA_GBM_u133a_overall.rds")
TCGA_GBM_rna_seq_overall = readRDS("data/TCGA_GBM_rna_seq_overall.rds")
TCGA_GBM_agilent_overall=readRDS("data/TCGA_GBM_agilent_overall.rds")
TCGA_LGG_overall=readRDS("data/TCGA_LGG_overall.rds")
Ivygap=readRDS("data/IvyGAP_gene_expression.rds")

# Read in the gene names files.
U133aoverallgenenames <- read.csv("data/U133aoverallgenenames.csv")
RNAoverallgenenames <- read.csv("data/RNAoverallgenenames.csv")
agilentoverallgenenames <- read.csv("data/agilentoverallgenenames.csv")
lggoverallgenenames <- read.csv("data/lggoverallgenenames.csv")
ivygapgenenames<-read.csv("data/ivygapgenenames.csv")

